-- ============================================================
-- ML Training Service - Vollständiges Datenbank-Schema
-- Version: 2.1 (Stand: 2024-12-23)
-- Enthält alle Migrationen, Erweiterungen und Verbesserungen
-- 
-- Verbesserungen (Phase 1):
-- - CHECK Constraints für Datenintegrität
-- - Zusätzliche Indizes für Performance
-- ============================================================

-- ============================================================
-- 1. ml_models - Modelle
-- ============================================================
CREATE TABLE IF NOT EXISTS ml_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    model_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'TRAINING',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    
    -- Training-Konfiguration
    target_variable VARCHAR(100) NOT NULL,
    target_operator VARCHAR(10),  -- Optional für zeitbasierte Vorhersagen (NULL erlaubt)
    target_value NUMERIC(20, 2),  -- Optional für zeitbasierte Vorhersagen (NULL erlaubt)
    train_start TIMESTAMP WITH TIME ZONE NOT NULL,
    train_end TIMESTAMP WITH TIME ZONE NOT NULL,
    test_size NUMERIC(3, 2),
    random_state INT,
    
    -- Zeitbasierte Vorhersage-Parameter (Migration: migration_add_time_based_columns.sql)
    future_minutes INTEGER,
    price_change_percent NUMERIC(10, 4),
    target_direction VARCHAR(10),
    
    -- Listen und Dicts als JSONB (nativ PostgreSQL)
    features JSONB NOT NULL,              -- ["price_open", "price_high", "price_low", "volume_sol"]
    phases JSONB,                         -- [1, 2, 3] 
    params JSONB,                         -- {"n_estimators": 100, "max_depth": 10, "min_samples": 5}
    feature_importance JSONB,             -- {"price_open": 0.35, "volume_sol": 0.25, "price_high": 0.20}
    
    -- Basis Performance-Metriken
    training_accuracy NUMERIC(5, 4),
    training_f1 NUMERIC(5, 4),
    training_precision NUMERIC(5, 4),
    training_recall NUMERIC(5, 4),
    
    -- Cross-Validation Metriken (Migration: migration_add_cv_scores.sql)
    cv_scores JSONB,                      -- {"train_accuracy": [...], "test_accuracy": [...], ...}
    cv_overfitting_gap NUMERIC(5, 4),     -- Differenz zwischen Train- und Test-Accuracy (Overfitting-Indikator)
    
    -- Zusätzliche Metriken (Migration: migration_add_additional_metrics.sql)
    roc_auc NUMERIC(5, 4),                -- ROC-AUC Score
    mcc NUMERIC(5, 4),                    -- Matthews Correlation Coefficient
    fpr NUMERIC(5, 4),                    -- False Positive Rate
    fnr NUMERIC(5, 4),                    -- False Negative Rate
    confusion_matrix JSONB,               -- {"tp": int, "tn": int, "fp": int, "fn": int}
    simulated_profit_pct NUMERIC(10, 4),  -- Simulierter Profit in Prozent
    
    -- Sonstiges
    model_file_path TEXT,
    description TEXT,
    
    CONSTRAINT chk_model_type CHECK (model_type IN ('random_forest', 'xgboost', 'gradient_boosting', 'logistic_regression', 'neural_network')),
    CONSTRAINT chk_status CHECK (status IN ('TRAINING', 'READY', 'FAILED')),
    CONSTRAINT chk_operator CHECK (target_operator IS NULL OR target_operator IN ('>', '<', '>=', '<=', '=')),
    CONSTRAINT chk_target_direction CHECK (target_direction IS NULL OR target_direction IN ('up', 'down')),
    -- Datenintegrität-Constraints (Phase 1)
    CONSTRAINT chk_future_minutes CHECK (future_minutes IS NULL OR future_minutes > 0),
    CONSTRAINT chk_price_change_percent CHECK (price_change_percent IS NULL OR price_change_percent > 0)
);

CREATE INDEX idx_models_status ON ml_models(status) WHERE is_deleted = FALSE;
CREATE INDEX idx_models_created ON ml_models(created_at DESC);

-- ============================================================
-- 2. ml_test_results - Test-Ergebnisse
-- ============================================================
CREATE TABLE IF NOT EXISTS ml_test_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL REFERENCES ml_models(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Zeitraum
    test_start TIMESTAMP WITH TIME ZONE NOT NULL,
    test_end TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Basis Metriken
    accuracy NUMERIC(5, 4),
    f1_score NUMERIC(5, 4),
    precision_score NUMERIC(5, 4),
    recall NUMERIC(5, 4),
    roc_auc NUMERIC(5, 4),
    
    -- Zusätzliche Metriken (Migration: migration_add_test_metrics.sql)
    mcc NUMERIC(5, 4),                        -- Matthews Correlation Coefficient
    fpr NUMERIC(5, 4),                        -- False Positive Rate
    fnr NUMERIC(5, 4),                        -- False Negative Rate
    simulated_profit_pct NUMERIC(10, 4),      -- Simulierter Profit in Prozent
    
    -- Confusion Matrix (einzelne Spalten + JSONB)
    tp INT,
    tn INT,
    fp INT,
    fn INT,
    confusion_matrix JSONB,                   -- {"tp": 1234, "tn": 5678, "fp": 890, "fn": 198}
    
    -- Samples
    num_samples INT,
    num_positive INT,
    num_negative INT,
    
    -- Overlap-Check
    has_overlap BOOLEAN DEFAULT FALSE,
    overlap_note TEXT,
    
    -- Train vs. Test Vergleich (Migration: migration_add_train_test_comparison.sql)
    train_accuracy NUMERIC(5, 4),            -- Training Accuracy (aus ml_models)
    train_f1 NUMERIC(5, 4),                   -- Training F1 (aus ml_models)
    train_precision NUMERIC(5, 4),           -- Training Precision (aus ml_models)
    train_recall NUMERIC(5, 4),              -- Training Recall (aus ml_models)
    accuracy_degradation NUMERIC(5, 4),       -- Train - Test Accuracy (Overfitting-Indikator)
    f1_degradation NUMERIC(5, 4),            -- Train - Test F1
    is_overfitted BOOLEAN,                    -- True wenn accuracy_degradation > 0.1
    
    -- Test-Zeitraum Info
    test_duration_days NUMERIC(10, 2),       -- Test-Zeitraum in Tagen
    
    -- Feature Importance als JSONB
    feature_importance JSONB,                 -- {"price_open": 0.35, "volume_sol": 0.25}
    
    -- Datenintegrität-Constraints (Phase 1)
    CONSTRAINT chk_test_dates CHECK (test_start < test_end),
    CONSTRAINT chk_test_duration CHECK (test_duration_days IS NULL OR test_duration_days >= 0)
);

CREATE INDEX idx_test_results_model ON ml_test_results(model_id);
CREATE INDEX idx_test_results_created ON ml_test_results(created_at DESC);
-- Performance-Index (Phase 1)
CREATE INDEX IF NOT EXISTS idx_test_results_model_created ON ml_test_results(model_id, created_at DESC);

-- ============================================================
-- 3. ml_comparisons - Modell-Vergleiche
-- ============================================================
CREATE TABLE IF NOT EXISTS ml_comparisons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Die beiden Modelle
    model_a_id BIGINT NOT NULL REFERENCES ml_models(id) ON DELETE CASCADE,
    model_b_id BIGINT NOT NULL REFERENCES ml_models(id) ON DELETE CASCADE,
    
    -- Zeitraum (gleich für beide)
    test_start TIMESTAMP WITH TIME ZONE NOT NULL,
    test_end TIMESTAMP WITH TIME ZONE NOT NULL,
    num_samples INT,
    
    -- Basis Metriken Modell A
    a_accuracy NUMERIC(5, 4),
    a_f1 NUMERIC(5, 4),
    a_precision NUMERIC(5, 4),
    a_recall NUMERIC(5, 4),
    
    -- Basis Metriken Modell B
    b_accuracy NUMERIC(5, 4),
    b_f1 NUMERIC(5, 4),
    b_precision NUMERIC(5, 4),
    b_recall NUMERIC(5, 4),
    
    -- Zusätzliche Metriken Modell A (Migration: migration_add_comparison_metrics.sql)
    a_mcc NUMERIC(5, 4),
    a_fpr NUMERIC(5, 4),
    a_fnr NUMERIC(5, 4),
    a_simulated_profit_pct NUMERIC(10, 4),
    a_confusion_matrix JSONB,
    a_train_accuracy NUMERIC(5, 4),
    a_train_f1 NUMERIC(5, 4),
    a_accuracy_degradation NUMERIC(5, 4),
    a_f1_degradation NUMERIC(5, 4),
    a_is_overfitted BOOLEAN,
    a_test_duration_days NUMERIC(10, 2),
    
    -- Zusätzliche Metriken Modell B (Migration: migration_add_comparison_metrics.sql)
    b_mcc NUMERIC(5, 4),
    b_fpr NUMERIC(5, 4),
    b_fnr NUMERIC(5, 4),
    b_simulated_profit_pct NUMERIC(10, 4),
    b_confusion_matrix JSONB,
    b_train_accuracy NUMERIC(5, 4),
    b_train_f1 NUMERIC(5, 4),
    b_accuracy_degradation NUMERIC(5, 4),
    b_f1_degradation NUMERIC(5, 4),
    b_is_overfitted BOOLEAN,
    b_test_duration_days NUMERIC(10, 2),
    
    -- Gewinner
    winner_id BIGINT REFERENCES ml_models(id),
    
    CONSTRAINT chk_different_models CHECK (model_a_id != model_b_id),
    -- Datenintegrität-Constraint (Phase 1)
    CONSTRAINT chk_compare_dates CHECK (test_start < test_end)
);

CREATE INDEX idx_comparisons_models ON ml_comparisons(model_a_id, model_b_id);
CREATE INDEX idx_comparisons_created ON ml_comparisons(created_at DESC);
-- Performance-Indizes (Phase 1)
CREATE INDEX IF NOT EXISTS idx_comparisons_winner ON ml_comparisons(winner_id) WHERE winner_id IS NOT NULL;

-- ============================================================
-- 4. ml_jobs - Warteschlange (alle Job-Typen vereint)
-- ============================================================
CREATE TABLE IF NOT EXISTS ml_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    priority INT DEFAULT 5,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    
    -- Fortschritt
    progress NUMERIC(3, 2) DEFAULT 0.0,
    progress_msg TEXT,
    
    -- Fehler
    error_msg TEXT,
    
    -- Worker
    worker_id VARCHAR(100),
    
    -- ========================================
    -- Job-spezifische Felder (je nach job_type)
    -- ========================================
    
    -- Für TRAIN: Konfiguration
    train_target_var VARCHAR(100),
    train_operator VARCHAR(10),
    train_value NUMERIC(20, 2),
    train_start TIMESTAMP WITH TIME ZONE,
    train_end TIMESTAMP WITH TIME ZONE,
    train_features JSONB,                  -- ["price_open", "price_high", "volume_sol"]
    train_phases JSONB,                    -- [1, 2, 3]
    train_params JSONB,                    -- {"n_estimators": 100, "max_depth": 10}
    train_model_type VARCHAR(50),
    
    -- Für TRAIN: Zeitbasierte Vorhersage-Parameter (Migration: migration_add_time_based_columns.sql)
    train_future_minutes INTEGER,
    train_price_change_percent NUMERIC(10, 4),
    train_target_direction VARCHAR(10),
    
    -- Für TRAIN: Ergebnis
    result_model_id BIGINT REFERENCES ml_models(id) ON DELETE SET NULL,
    
    -- Für TEST: Konfiguration
    test_model_id BIGINT REFERENCES ml_models(id) ON DELETE CASCADE,
    test_start TIMESTAMP WITH TIME ZONE,
    test_end TIMESTAMP WITH TIME ZONE,
    
    -- Für TEST: Ergebnis
    result_test_id BIGINT REFERENCES ml_test_results(id) ON DELETE SET NULL,
    
    -- Für COMPARE: Konfiguration
    compare_model_a_id BIGINT REFERENCES ml_models(id) ON DELETE CASCADE,
    compare_model_b_id BIGINT REFERENCES ml_models(id) ON DELETE CASCADE,
    compare_start TIMESTAMP WITH TIME ZONE,
    compare_end TIMESTAMP WITH TIME ZONE,
    
    -- Für COMPARE: Ergebnis
    result_comparison_id BIGINT REFERENCES ml_comparisons(id) ON DELETE SET NULL,
    
    CONSTRAINT chk_job_type CHECK (job_type IN ('TRAIN', 'TEST', 'COMPARE')),
    CONSTRAINT chk_job_status CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    CONSTRAINT chk_train_target_direction CHECK (train_target_direction IS NULL OR train_target_direction IN ('up', 'down')),
    -- Datenintegrität-Constraints (Phase 1)
    CONSTRAINT chk_train_dates CHECK (train_start IS NULL OR train_end IS NULL OR train_start < train_end),
    CONSTRAINT chk_test_job_dates CHECK (test_start IS NULL OR test_end IS NULL OR test_start < test_end),
    CONSTRAINT chk_compare_job_dates CHECK (compare_start IS NULL OR compare_end IS NULL OR compare_start < compare_end),
    CONSTRAINT chk_train_future_minutes CHECK (train_future_minutes IS NULL OR train_future_minutes > 0),
    CONSTRAINT chk_train_price_change_percent CHECK (train_price_change_percent IS NULL OR train_price_change_percent > 0)
);

CREATE INDEX idx_jobs_status ON ml_jobs(status, priority, created_at) WHERE status IN ('PENDING', 'RUNNING');
CREATE INDEX idx_jobs_created ON ml_jobs(created_at DESC);
-- Performance-Index (Phase 1)
CREATE INDEX IF NOT EXISTS idx_jobs_type_status ON ml_jobs(job_type, status, created_at DESC);

-- ============================================================
-- 5. ref_model_types - Referenztabelle für Modell-Typen
-- ============================================================
CREATE TABLE IF NOT EXISTS ref_model_types (
    id INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    default_params JSONB                   -- {"n_estimators": 100, "max_depth": 10}
);

INSERT INTO ref_model_types (id, name, description, default_params) VALUES
(1, 'random_forest', 'Random Forest Classifier', '{"n_estimators": 100, "max_depth": 10, "min_samples_split": 2}'::jsonb),
(2, 'xgboost', 'XGBoost Classifier', '{"n_estimators": 100, "max_depth": 6, "learning_rate": 0.1}'::jsonb),
(3, 'gradient_boosting', 'Gradient Boosting Classifier', '{"n_estimators": 100, "max_depth": 3, "learning_rate": 0.1}'::jsonb),
(4, 'logistic_regression', 'Logistic Regression', '{"C": 1.0, "max_iter": 100}'::jsonb),
(5, 'neural_network', 'Neural Network (MLP)', '{"hidden_layers": [100, 50], "activation": "relu", "max_iter": 200}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- KOMMENTARE
-- ============================================================
COMMENT ON TABLE ml_models IS 'ML-Modelle mit Training-Konfiguration. Listen und Dicts als JSONB. Enthält alle Metriken und zeitbasierte Vorhersage-Parameter.';
COMMENT ON TABLE ml_test_results IS 'Test-Ergebnisse mit Metriken. Feature Importance als JSONB. Enthält Train vs. Test Vergleich.';
COMMENT ON TABLE ml_comparisons IS 'Vergleiche zwischen zwei Modellen mit Metriken pro Modell. Enthält alle zusätzlichen Metriken.';
COMMENT ON TABLE ml_jobs IS 'Alle Jobs (TRAIN/TEST/COMPARE) mit typ-spezifischen Feldern. Enthält zeitbasierte Vorhersage-Parameter.';
COMMENT ON TABLE ref_model_types IS 'Referenztabelle mit Standard-Parametern pro Modell-Typ als JSONB.';

-- ml_models Kommentare
COMMENT ON COLUMN ml_models.features IS 'JSONB Array: ["price_open", "price_high", "price_low", "volume_sol"]';
COMMENT ON COLUMN ml_models.phases IS 'JSONB Array: [1, 2, 3] (Referenz zu ref_coin_phases)';
COMMENT ON COLUMN ml_models.params IS 'JSONB Object: {"n_estimators": 100, "max_depth": 10}';
COMMENT ON COLUMN ml_models.feature_importance IS 'JSONB Object: {"price_open": 0.35, "volume_sol": 0.25}';
COMMENT ON COLUMN ml_models.cv_scores IS 'JSONB Object: Cross-Validation Ergebnisse {"train_accuracy": [...], "test_accuracy": [...], ...}';
COMMENT ON COLUMN ml_models.cv_overfitting_gap IS 'Differenz zwischen Train- und Test-Accuracy (Overfitting-Indikator)';
COMMENT ON COLUMN ml_models.roc_auc IS 'ROC-AUC Score (Receiver Operating Characteristic - Area Under Curve)';
COMMENT ON COLUMN ml_models.mcc IS 'Matthews Correlation Coefficient (besser für imbalanced data)';
COMMENT ON COLUMN ml_models.fpr IS 'False Positive Rate (wichtig für Pump-Detection)';
COMMENT ON COLUMN ml_models.fnr IS 'False Negative Rate';
COMMENT ON COLUMN ml_models.confusion_matrix IS 'JSONB Object: {"tp": int, "tn": int, "fp": int, "fn": int}';
COMMENT ON COLUMN ml_models.simulated_profit_pct IS 'Simulierter Profit in Prozent (vereinfachte Simulation)';
COMMENT ON COLUMN ml_models.future_minutes IS 'Anzahl Minuten in die Zukunft für zeitbasierte Vorhersage (z.B. 10)';
COMMENT ON COLUMN ml_models.price_change_percent IS 'Mindest-Prozent-Änderung für zeitbasierte Vorhersage (z.B. 5.0)';
COMMENT ON COLUMN ml_models.target_direction IS 'Richtung der Vorhersage: "up" oder "down"';

-- ml_test_results Kommentare
COMMENT ON COLUMN ml_test_results.confusion_matrix IS 'JSONB Object: {"tp": 1234, "tn": 5678, "fp": 890, "fn": 198}';
COMMENT ON COLUMN ml_test_results.mcc IS 'Matthews Correlation Coefficient (besser für imbalanced data)';
COMMENT ON COLUMN ml_test_results.fpr IS 'False Positive Rate (wichtig für Pump-Detection)';
COMMENT ON COLUMN ml_test_results.fnr IS 'False Negative Rate';
COMMENT ON COLUMN ml_test_results.simulated_profit_pct IS 'Simulierter Profit in Prozent (1% Gewinn pro TP, -0.5% Verlust pro FP)';
COMMENT ON COLUMN ml_test_results.train_accuracy IS 'Training Accuracy (aus ml_models) für Train vs. Test Vergleich';
COMMENT ON COLUMN ml_test_results.train_f1 IS 'Training F1 (aus ml_models) für Train vs. Test Vergleich';
COMMENT ON COLUMN ml_test_results.accuracy_degradation IS 'Accuracy Degradation (Test - Train) - Overfitting-Indikator';
COMMENT ON COLUMN ml_test_results.is_overfitted IS 'True wenn accuracy_degradation > 0.1';
COMMENT ON COLUMN ml_test_results.test_duration_days IS 'Test-Zeitraum Dauer in Tagen';

-- ml_comparisons Kommentare
COMMENT ON COLUMN ml_comparisons.a_mcc IS 'Matthews Correlation Coefficient für Modell A';
COMMENT ON COLUMN ml_comparisons.a_fpr IS 'False Positive Rate für Modell A';
COMMENT ON COLUMN ml_comparisons.a_fnr IS 'False Negative Rate für Modell A';
COMMENT ON COLUMN ml_comparisons.a_simulated_profit_pct IS 'Simulierter Profit in Prozent für Modell A';
COMMENT ON COLUMN ml_comparisons.a_confusion_matrix IS 'Confusion Matrix als JSONB für Modell A: {"tp": 1234, "tn": 5678, "fp": 890, "fn": 198}';
COMMENT ON COLUMN ml_comparisons.a_train_accuracy IS 'Train Accuracy für Modell A (für Train vs. Test Vergleich)';
COMMENT ON COLUMN ml_comparisons.a_train_f1 IS 'Train F1 für Modell A (für Train vs. Test Vergleich)';
COMMENT ON COLUMN ml_comparisons.a_accuracy_degradation IS 'Accuracy Degradation (Test - Train) für Modell A';
COMMENT ON COLUMN ml_comparisons.a_f1_degradation IS 'F1 Degradation (Test - Train) für Modell A';
COMMENT ON COLUMN ml_comparisons.a_is_overfitted IS 'Ist Modell A overfitted? (basierend auf accuracy_degradation > 0.1)';
COMMENT ON COLUMN ml_comparisons.a_test_duration_days IS 'Test-Zeitraum Dauer in Tagen für Modell A';
COMMENT ON COLUMN ml_comparisons.b_mcc IS 'Matthews Correlation Coefficient für Modell B';
COMMENT ON COLUMN ml_comparisons.b_fpr IS 'False Positive Rate für Modell B';
COMMENT ON COLUMN ml_comparisons.b_fnr IS 'False Negative Rate für Modell B';
COMMENT ON COLUMN ml_comparisons.b_simulated_profit_pct IS 'Simulierter Profit in Prozent für Modell B';
COMMENT ON COLUMN ml_comparisons.b_confusion_matrix IS 'Confusion Matrix als JSONB für Modell B: {"tp": 1234, "tn": 5678, "fp": 890, "fn": 198}';
COMMENT ON COLUMN ml_comparisons.b_train_accuracy IS 'Train Accuracy für Modell B (für Train vs. Test Vergleich)';
COMMENT ON COLUMN ml_comparisons.b_train_f1 IS 'Train F1 für Modell B (für Train vs. Test Vergleich)';
COMMENT ON COLUMN ml_comparisons.b_accuracy_degradation IS 'Accuracy Degradation (Test - Train) für Modell B';
COMMENT ON COLUMN ml_comparisons.b_f1_degradation IS 'F1 Degradation (Test - Train) für Modell B';
COMMENT ON COLUMN ml_comparisons.b_is_overfitted IS 'Ist Modell B overfitted? (basierend auf accuracy_degradation > 0.1)';
COMMENT ON COLUMN ml_comparisons.b_test_duration_days IS 'Test-Zeitraum Dauer in Tagen für Modell B';

-- ml_jobs Kommentare
COMMENT ON COLUMN ml_jobs.train_future_minutes IS 'Anzahl Minuten in die Zukunft für zeitbasierte Vorhersage (Training)';
COMMENT ON COLUMN ml_jobs.train_price_change_percent IS 'Mindest-Prozent-Änderung für zeitbasierte Vorhersage (Training)';
COMMENT ON COLUMN ml_jobs.train_target_direction IS 'Richtung der Vorhersage: "up" oder "down" (Training)';
